export enum TransactionType {
  APPROVE = "APPROVE",
  SWAP = "SWAP",
  START_FARMING = "START_FARMING",
  STOP_FARMING = "STOP_FARMING",
  STAKING = "STAKING",
  UNSTAKING = "UNSTAKING",
  CLAIM = "CLAIM",
  SIGN ="SIGN"
}
