name: Security Audit
on:
  push:
  pull_request:

jobs:
  audits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: npm audit
        run: npm audit --omit=dev || true

      - name: Setup Python & install semgrep
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install semgrep
          semgrep --config=p/javascript --severity=ERROR . || true

      - name: Run Lighthouse
        run: |
          npm install -g lighthouse
          lighthouse https://birdieswap-dev.vercel.app --output html --output-path=lh-report.html --preset=desktop
      - uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: lh-report.html

      - name: Run OWASP ZAP Baseline
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "https://birdieswap-dev.vercel.app"
          rules_file_name: ".zap/rules.tsv"
          cmd_options: "-a"
      - uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html
