name: Semgrep

on:
  pull_request:
  push:
    branches: [ "main", "dev_fe" ]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install semgrep
          # 기본 보안 규칙 + JS/TS
          semgrep --config=p/ci --config=p/javascript --severity=ERROR . || true
